server:
  port: 0 #랜덤 포트
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: catalog-service # MSA 고유 아이디
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true

my-kafka:
  group-id: consumerGroupId
