server:
  port: 8761

spring:
  application:
    name: discoveryservice # MSA 고유 아이디
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: false # 현재 프로젝트 Discovery Service 미등록(서버로서 기동만 되어 있으면 되기 때문에), Default true
    fetch-registry: false # EUREKA 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것을 미설정, Default true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh