token:
  expiration_time: 86400000
  secret: "{cipher}edb6d5c1d7a71c5b93a080bb1c553f2f245c5c60d01b2f0dc666c4e7f68b8620"
  header: X-Authorization-Id

server:
  port: 0 #랜덤 포트
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: user-service # MSA 고유 아이디
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    me.study.userservice.client: DEBUG